spring:
  application:
    name: mscustomer
  datasource:
    url: jdbc:postgresql://localhost:5432/mscustomer
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database:
      plataform: org.hibernate.dialect.PostgreSQLDialect



